# SPDX-FileCopyrightText: Copyright 2026 Todd Schulman
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = "blackoutd-diag-*/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2026 Todd Schulman"
SPDX-License-Identifier = "GPL-3.0-or-later"
